// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230909090953_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RoleID");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = "account01",
                            Email = "XxArmCustomerxX@gmail.com",
                            FirstName = "ArmCustomer",
                            ImageUrl = "https://cv.lnwfile.com/_/cv/_raw/rn/s7/3p.png",
                            LastName = "Kung",
                            LoginBy = "",
                            Password = "Mw52so+8rK3NMGo/MDb85w==.7Rxql67dW+VxjYSja2uusRgJy860Q0KKTD0RyA9ju8Q=",
                            PhoneNumber = "0616032203",
                            RoleID = 1,
                            Status = true
                        },
                        new
                        {
                            Id = "account02",
                            Email = "XxArmSellerxX@gmail.com",
                            FirstName = "ArmSeller",
                            ImageUrl = "https://cv.lnwfile.com/_/cv/_raw/rn/s7/3p.png",
                            LastName = "Kung",
                            LoginBy = "",
                            Password = "Mw52so+8rK3NMGo/MDb85w==.7Rxql67dW+VxjYSja2uusRgJy860Q0KKTD0RyA9ju8Q=",
                            PhoneNumber = "0616032203",
                            RoleID = 2,
                            Status = true
                        },
                        new
                        {
                            Id = "account03",
                            Email = "XxArmAdminxX@gmail.com",
                            FirstName = "ArmAdmin",
                            ImageUrl = "https://cv.lnwfile.com/_/cv/_raw/rn/s7/3p.png",
                            LastName = "Kung",
                            LoginBy = "",
                            Password = "Mw52so+8rK3NMGo/MDb85w==.7Rxql67dW+VxjYSja2uusRgJy860Q0KKTD0RyA9ju8Q=",
                            PhoneNumber = "0616032203",
                            RoleID = 3,
                            Status = true
                        });
                });

            modelBuilder.Entity("WebApi.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AddressInformationsId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccountID");

                    b.HasIndex("AddressInformationsId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("WebApi.Models.AddressInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AddressInformations");
                });

            modelBuilder.Entity("WebApi.Models.CategoryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryProducts");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "มังคุด"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ลำไย"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ทุเรียน"
                        },
                        new
                        {
                            Id = 5,
                            Name = "เงาะ"
                        },
                        new
                        {
                            Id = 6,
                            Name = "มะม่วง"
                        },
                        new
                        {
                            Id = 7,
                            Name = "กล้วย"
                        },
                        new
                        {
                            Id = 8,
                            Name = "มะพร้าว"
                        },
                        new
                        {
                            Id = 9,
                            Name = "ขนุน"
                        },
                        new
                        {
                            Id = 10,
                            Name = "หมาก"
                        },
                        new
                        {
                            Id = 11,
                            Name = "มะละกอ"
                        },
                        new
                        {
                            Id = 12,
                            Name = "น้อยหน่า"
                        },
                        new
                        {
                            Id = 13,
                            Name = "ลองกอง"
                        },
                        new
                        {
                            Id = 14,
                            Name = "ส้ม"
                        },
                        new
                        {
                            Id = 15,
                            Name = "ชมพู่"
                        },
                        new
                        {
                            Id = 16,
                            Name = "ขนุน"
                        },
                        new
                        {
                            Id = 999,
                            Name = "หายาก"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShippingServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusDeliveryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeArrive")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderID");

                    b.HasIndex("StatusDeliveryID");

                    b.ToTable("Deliverys");
                });

            modelBuilder.Entity("WebApi.Models.DetailProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FertilizeMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrowingSeason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HarvestTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantingMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.ToTable("DetailProducts");
                });

            modelBuilder.Entity("WebApi.Models.EvidenceMoneyTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OrderID");

                    b.ToTable("EvidenceMoneyTransfers");
                });

            modelBuilder.Entity("WebApi.Models.ImageProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.ToTable("ImageProducts");
                });

            modelBuilder.Entity("WebApi.Models.ImageReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewID");

                    b.ToTable("ImageReviews");
                });

            modelBuilder.Entity("WebApi.Models.LevelProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LevelProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = "หาได้ทั่วไป"
                        },
                        new
                        {
                            Id = 2,
                            Level = "ปานกลาง"
                        },
                        new
                        {
                            Id = 3,
                            Level = "หายาก"
                        });
                });

            modelBuilder.Entity("WebApi.Models.OrderAggregate.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CustomerStatus")
                        .HasColumnType("bit");

                    b.Property<long>("DeliveryFee")
                        .HasColumnType("bigint");

                    b.Property<bool>("OrderCancel")
                        .HasColumnType("bit");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("OrderUsage")
                        .HasColumnType("int");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<bool>("SellerStatus")
                        .HasColumnType("bit");

                    b.Property<long>("Subtotal")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebApi.Models.OrderAggregate.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("WebApi.Models.OrderAggregate.OrderMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderMessages");
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryProductID")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LevelProductID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.Property<int>("WeightUnitID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryProductID");

                    b.HasIndex("LevelProductID");

                    b.HasIndex("WeightUnitID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "product01",
                            AccountID = "account01",
                            CategoryProductID = 2,
                            Color = "เขียว",
                            Created = new DateTime(2023, 9, 9, 16, 9, 53, 585, DateTimeKind.Local).AddTicks(8866),
                            Description = "อร่อย",
                            ImageUrl = "https://www.ตลาดกลางผลไม้.com/wp-content/uploads/2019/10/72414759_106730297406260_6103449987075538944_n.jpg",
                            LevelProductID = 1,
                            Name = "ส้มโอทับทิมสยาม",
                            Price = 150,
                            Stock = 50,
                            Weight = 1.0,
                            WeightUnitID = 1
                        },
                        new
                        {
                            Id = "product02",
                            AccountID = "account01",
                            CategoryProductID = 2,
                            Color = "เขียว",
                            Created = new DateTime(2023, 9, 9, 16, 9, 53, 585, DateTimeKind.Local).AddTicks(8889),
                            Description = "อร่อย",
                            ImageUrl = "https://scontent-sin6-4.xx.fbcdn.net/v/t39.30808-6/299863661_433735048781055_6878774558773361005_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=3DcFFDZIL-0AX_oGgNx&_nc_ht=scontent-sin6-4.xx&oh=00_AfDQhZa4WiqXQ5mbCx6057-jHaiFA7Llf5Caf9UuFfyl9w&oe=64EC700D",
                            LevelProductID = 1,
                            Name = "กล้วยน้ำว้ามะลิอ่อง",
                            Price = 150,
                            Stock = 50,
                            Weight = 1.0,
                            WeightUnitID = 1
                        },
                        new
                        {
                            Id = "product03",
                            AccountID = "account01",
                            CategoryProductID = 2,
                            Color = "เขียว",
                            Created = new DateTime(2023, 9, 9, 16, 9, 53, 585, DateTimeKind.Local).AddTicks(8892),
                            Description = "อร่อย",
                            ImageUrl = "https://cdn.shortpixel.ai/spai/w_870+q_lossy+ret_img+to_webp/amprohealth.com/wp-content/uploads/2017/09/135-%E0%B9%80%E0%B8%AA%E0%B8%B2%E0%B8%A7%E0%B8%A3%E0%B8%AA.jpg",
                            LevelProductID = 1,
                            Name = "เสาวรส",
                            Price = 150,
                            Stock = 50,
                            Weight = 1.0,
                            WeightUnitID = 1
                        },
                        new
                        {
                            Id = "product04",
                            AccountID = "account01",
                            CategoryProductID = 2,
                            Color = "ม่วง",
                            Created = new DateTime(2023, 9, 9, 16, 9, 53, 585, DateTimeKind.Local).AddTicks(8893),
                            Description = "อร่อย",
                            ImageUrl = "https://ตลาดเกษตรกรออนไลน์.com/uploads/products/cover_6285c7898575f.jpg",
                            LevelProductID = 1,
                            Name = "มังคุดสด มาตรฐาน GAP",
                            Price = 250,
                            Stock = 50,
                            Weight = 1.0,
                            WeightUnitID = 1
                        },
                        new
                        {
                            Id = "product05",
                            AccountID = "account01",
                            CategoryProductID = 2,
                            Color = "เหลืองทอง",
                            Created = new DateTime(2023, 9, 9, 16, 9, 53, 585, DateTimeKind.Local).AddTicks(8895),
                            Description = "อร่อย",
                            ImageUrl = "https://dk8dmtco5sckz.cloudfront.net/wp-content/uploads/2023/03/AnyConv.com__15-8.webp",
                            LevelProductID = 1,
                            Name = "ทุเรียนหมอนทอง",
                            Price = 250,
                            Stock = 50,
                            Weight = 1.0,
                            WeightUnitID = 1
                        },
                        new
                        {
                            Id = "product06",
                            AccountID = "account01",
                            CategoryProductID = 3,
                            Color = "เหลืองทอง",
                            Created = new DateTime(2023, 9, 9, 16, 9, 53, 585, DateTimeKind.Local).AddTicks(8897),
                            Description = "อร่อย",
                            ImageUrl = "https://www.ตลาดเกษตรกรออนไลน์.com/uploads/products/cover_64914f3b033fd.jpg",
                            LevelProductID = 1,
                            Name = "แก้วมังกร",
                            Price = 250,
                            Stock = 50,
                            Weight = 1.0,
                            WeightUnitID = 1
                        },
                        new
                        {
                            Id = "product07",
                            AccountID = "account01",
                            CategoryProductID = 3,
                            Color = "เหลืองทอง",
                            Created = new DateTime(2023, 9, 9, 16, 9, 53, 585, DateTimeKind.Local).AddTicks(8899),
                            Description = "หวานฉ่ำชื่นใจ ไม่แสบคอ เนื้อเยอะ เม็ดลีบ แห้งไม่แฉะ",
                            ImageUrl = "https://www.ตลาดเกษตรกรออนไลน์.com/uploads/products/cover_64914f3b033fd.jpg",
                            LevelProductID = 1,
                            Name = "ลำไยอีดอ",
                            Price = 250,
                            Stock = 50,
                            Weight = 1.0,
                            WeightUnitID = 1
                        },
                        new
                        {
                            Id = "product08",
                            AccountID = "account03",
                            CategoryProductID = 999,
                            Color = "เลือดหมู",
                            Created = new DateTime(2023, 9, 9, 16, 9, 53, 585, DateTimeKind.Local).AddTicks(8901),
                            Description = "หวานฉ่ำชื่นใจ ไม่แสบคอ เนื้อเยอะ เม็ดลีบ แห้งไม่แฉะ",
                            ImageUrl = "https://www.77kaoded.com/wp-content/uploads/2021/08/IMG_5061.jpg",
                            LevelProductID = 1,
                            Name = "เสาวรส",
                            Price = 250,
                            Stock = 50,
                            Weight = 1.0,
                            WeightUnitID = 1
                        },
                        new
                        {
                            Id = "product09",
                            AccountID = "account01",
                            CategoryProductID = 3,
                            Color = "เหลือง",
                            Created = new DateTime(2023, 9, 9, 16, 9, 53, 585, DateTimeKind.Local).AddTicks(8903),
                            Description = "อร่อย",
                            ImageUrl = "https://www.ตลาดเกษตรกรออนไลน์.com/uploads/products/398.jpg",
                            LevelProductID = 1,
                            Name = "เมล่อน",
                            Price = 250,
                            Stock = 50,
                            Weight = 1.0,
                            WeightUnitID = 1
                        });
                });

            modelBuilder.Entity("WebApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderItemID")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("VdoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("WebApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "customer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "seller"
                        },
                        new
                        {
                            Id = 3,
                            Name = "admin"
                        });
                });

            modelBuilder.Entity("WebApi.Models.StatusDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusDeliverys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "กำลังเตรียมพัสดุ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "บริษัทขนส่งเข้ารับพัสดุเรียบร้อยแล้ว"
                        },
                        new
                        {
                            Id = 3,
                            Name = "พัสดุถึงศูนย์คัดแยกสินค้า"
                        },
                        new
                        {
                            Id = 4,
                            Name = "พัสดุออกจากศูนย์คัดแยกสินค้า"
                        },
                        new
                        {
                            Id = 5,
                            Name = "พัสดุถึงสาขาปลายทาง"
                        },
                        new
                        {
                            Id = 999,
                            Name = "การจัดส่งสำเร็จ"
                        });
                });

            modelBuilder.Entity("WebApi.Models.WeightUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeightUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ลูก"
                        },
                        new
                        {
                            Id = 2,
                            Name = "กิโลกรัม"
                        });
                });

            modelBuilder.Entity("WebApi.Modes.CartAggregate.Cart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("WebApi.Modes.CartAggregate.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("WebApi.Models.Account", b =>
                {
                    b.HasOne("WebApi.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApi.Models.Address", b =>
                {
                    b.HasOne("WebApi.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.AddressInformation", "AddressInformations")
                        .WithMany()
                        .HasForeignKey("AddressInformationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("AddressInformations");
                });

            modelBuilder.Entity("WebApi.Models.Delivery", b =>
                {
                    b.HasOne("WebApi.Models.OrderAggregate.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.StatusDelivery", "StatusDelivery")
                        .WithMany()
                        .HasForeignKey("StatusDeliveryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("StatusDelivery");
                });

            modelBuilder.Entity("WebApi.Models.DetailProduct", b =>
                {
                    b.HasOne("WebApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApi.Models.EvidenceMoneyTransfer", b =>
                {
                    b.HasOne("WebApi.Models.OrderAggregate.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebApi.Models.ImageProduct", b =>
                {
                    b.HasOne("WebApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApi.Models.ImageReview", b =>
                {
                    b.HasOne("WebApi.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("WebApi.Models.OrderAggregate.Order", b =>
                {
                    b.HasOne("WebApi.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("WebApi.Models.OrderAggregate.OrderItem", b =>
                {
                    b.HasOne("WebApi.Models.OrderAggregate.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WebApi.Modes.OrderAggregate.ProductItemOrdered", "ItemOrdered", b1 =>
                        {
                            b1.Property<int>("OrderItemId")
                                .HasColumnType("int");

                            b1.Property<string>("ImageUrl")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ProductID")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("OrderItems");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("ItemOrdered")
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebApi.Models.OrderAggregate.OrderMessage", b =>
                {
                    b.HasOne("WebApi.Models.OrderAggregate.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.HasOne("WebApi.Models.CategoryProduct", "CategoryProduct")
                        .WithMany()
                        .HasForeignKey("CategoryProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.LevelProduct", "LevelProduct")
                        .WithMany()
                        .HasForeignKey("LevelProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.WeightUnit", "WeightUnit")
                        .WithMany()
                        .HasForeignKey("WeightUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryProduct");

                    b.Navigation("LevelProduct");

                    b.Navigation("WeightUnit");
                });

            modelBuilder.Entity("WebApi.Models.Review", b =>
                {
                    b.HasOne("WebApi.Models.OrderAggregate.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("WebApi.Modes.CartAggregate.Cart", b =>
                {
                    b.HasOne("WebApi.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("WebApi.Modes.CartAggregate.CartItem", b =>
                {
                    b.HasOne("WebApi.Modes.CartAggregate.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApi.Modes.CartAggregate.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
